[tool.poetry]
name = "CPRDisplaySystem"
version = "y"
description = "This is test project."
authors = ["Ginga Ishiguro"]

[tool.poetry.dependencies]
python = "3.7.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
